drop table IF EXISTS objectives CASCADE;

create table objectives (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  lat DOUBLE NOT NULL,
  lon DOUBLE NOT NULL,
  depth INTEGER NOT NULL,
  add_location INTEGER NOT NULL,
  step_grade INTEGER NOT NULL,
  radius INTEGER NOT NULL,
  step_radius INTEGER NOT NULL,
  CONSTRAINT pk_objective PRIMARY KEY (id)
  );

  create table speeds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, //думаю иожно обойтись без
    lat DOUBLE NOT NULL,
    lon DOUBLE NOT NULL,
    depth INTEGER NOT NULL,
    sound_speed INTEGER NOT NULL,
    CONSTRAINT pk_speed PRIMARY KEY (depth)
    );
