
 create table locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat DOUBLE NOT NULL,
  lon DOUBLE NOT NULL,
  CONSTRAINT pk_locations PRIMARY KEY (id)
  );

create table users (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE,
  CONSTRAINT pk_user PRIMARY KEY (id)
  );

create table pets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  owner_id integer NOT NULL REFERENCES users(id) ON delete CASCADE,
  city VARCHAR(255) NOT NULL,
  location_id integer NOT NULL REFERENCES locations(id) ON delete CASCADE,
  chip BOOLEAN NOT NULL,
  brand BOOLEAN NOT NULL,  //клеймо
  loss_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  description VARCHAR NOT NULL,
  CONSTRAINT pk_pet PRIMARY KEY (id)
  );